### ISSUE TITLE
custom_nodes\ComfyUI-Addoor module for custom nodes: 'gbk' codec can't decode byte 0xa4 in position 37: illegal multibyte sequence

### ISSUE THREAD

**Issue by YoungHYMX** [Eagle-CN/ComfyUI-Addoor#5]
custom_nodes\ComfyUI-Addoor module for custom nodes: 'gbk' codec can't decode byte 0xa4 in position 37: illegal multibyte sequence

**Comment by YoungHYMX** [comment]
File "E:\Comfyui\Comfyui\custom_nodes\ComfyUI-Addoor\rp\__init__.py", line 37, in load_nodes
    config.read(config_path)
  File "configparser.py", line 713, in read
  File "configparser.py", line 1036, in _read
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 37: illegal multibyte sequence

**Comment by Eagle-CN** [comment]
Please update to the latest version and try again.

**Comment by Terminator-AGI** [comment]
The latest version has the same error

Unexpected error in load_nodes: 'gbk' codec can't decode byte 0xa4 in position 37: illegal multibyte sequence
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Addoor\rp\__init__.py", line 45, in load_nodes
    config.read(config_path)
  File "configparser.py", line 713, in read
  File "configparser.py", line 1037, in _read
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 37: illegal multibyte sequence

Fixed! Find the config.ini file and delete the first line of Chinese characters
\custom_nodes\ComfyUI-Addoor\rp\config.ini

**Comment by YoungHYMX** [comment]
It's ok now.

**Comment by Eagle-CN** [comment]
Thank you, the issue has been fixed
